name: MedDuck
favicon: null
layout_spectrum: 0.8083390498068184
typography_spectrum: 0.9798814957030118
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.009662926197052002
  lightness: 0.2807685781735927
  saturation: 0.11162439198233187
  rhythmicContrast: 0.8383333152160048
purpose: []
